name: Build ZQ SFX Audio Splitter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pydub numpy

      - name: Clean Previous Builds
        run: |
          rm -rf build/ __pycache__/ *.spec
          rm -rf ffmpeg_dir ffmpeg.zip ffprobe.zip  # Remove existing FFmpeg files

      - name: Download FFmpeg and FFprobe
        shell: bash
        run: |
          echo "Downloading FFmpeg..."
          curl -L -o ffmpeg.zip https://evermeet.cx/ffmpeg/ffmpeg-6.0.zip
          echo "Downloading FFprobe..."
          curl -L -o ffprobe.zip https://evermeet.cx/ffmpeg/ffprobe-6.0.zip

          echo "Creating ffmpeg_dir directory..."
          mkdir -p ffmpeg_dir

          echo "Extracting FFmpeg..."
          unzip -j -o ffmpeg.zip -d ffmpeg_dir  # Extract directly into ffmpeg_dir
          echo "Extracting FFprobe..."
          unzip -j -o ffprobe.zip -d ffmpeg_dir  # Extract directly into ffmpeg_dir

          echo "Cleaning up..."
          rm -rf ffmpeg.zip ffprobe.zip

          echo "FFmpeg and FFprobe binaries downloaded and moved successfully."

      - name: Verify FFmpeg and FFprobe Binaries
        shell: bash
        run: |
          if [ -f "ffmpeg_dir/ffmpeg" ]; then
            echo "ffmpeg is present."
            chmod +x ffmpeg_dir/ffmpeg
          else
            echo "ffmpeg is missing." >&2
            exit 1
          fi

          if [ -f "ffmpeg_dir/ffprobe" ]; then
            echo "ffprobe is present."
            chmod +x ffmpeg_dir/ffprobe
          else
            echo "ffprobe is missing." >&2
            exit 1
          fi

          echo "Contents of ffmpeg_dir:"
          ls -la ffmpeg_dir

      - name: Build with PyInstaller
        run: |
          pyinstaller --windowed --onedir --distpath "./" --name "ZQ SFX Audio Splitter" audio_splitter_gui.py \
          --add-binary "ffmpeg_dir/ffmpeg:Resources" \
          --add-binary "ffmpeg_dir/ffprobe:Resources" \
          --hidden-import=tkinter \
          --hidden-import=pydub \
          --hidden-import=numpy \
          --exclude-module=test \
          --exclude-module=unittest \
          --exclude-module=email \
          --exclude-module=html \
          --exclude-module=xml \
          --log-level=DEBUG \
          --debug=all \
          --osx-bundle-identifier "com.github.themightyzq.ZQSFXAudioSplitter"

      - name: List Contents of App Bundle Before Moving
        shell: bash
        run: |
          echo "Listing contents of the app bundle before moving binaries:"
          find "ZQ SFX Audio Splitter.app" -print

      - name: Move FFmpeg and FFprobe to Resources
        shell: bash
        run: |
          echo "Moving ffmpeg and ffprobe to Resources..."
          mv "ZQ SFX Audio Splitter.app/Contents/Frameworks/Resources/ffmpeg" "ZQ SFX Audio Splitter.app/Contents/Resources/"
          mv "ZQ SFX Audio Splitter.app/Contents/Frameworks/Resources/ffprobe" "ZQ SFX Audio Splitter.app/Contents/Resources/"
          echo "Moved ffmpeg and ffprobe to Resources."

      - name: Confirm Move
        shell: bash
        run: |
          echo "Verifying move of ffmpeg and ffprobe to Resources..."
          ls -la "ZQ SFX Audio Splitter.app/Contents/Resources/"

      - name: Set Execute Permissions on macOS Executable and FFmpeg/FFprobe
        shell: bash
        run: |
          APP_PATH="ZQ SFX Audio Splitter.app/Contents/MacOS/ZQ SFX Audio Splitter"
          FFMPEG_PATH="ZQ SFX Audio Splitter.app/Contents/Resources/ffmpeg"
          FFPROBE_PATH="ZQ SFX Audio Splitter.app/Contents/Resources/ffprobe"
          if [ -f "$APP_PATH" ]; then
            chmod +x "$APP_PATH"
            echo "Set execute permissions on $APP_PATH"
          else
            echo "Executable not found at $APP_PATH" >&2
            ls -la "ZQ SFX Audio Splitter.app/Contents/MacOS"
            exit 1
          fi
          if [ -f "$FFMPEG_PATH" ]; then
            chmod +x "$FFMPEG_PATH"
            echo "Set execute permissions on $FFMPEG_PATH"
          else
            echo "FFmpeg not found at $FFMPEG_PATH" >&2
            ls -la "ZQ SFX Audio Splitter.app/Contents/Resources"
            exit 1
          fi
          if [ -f "$FFPROBE_PATH" ]; then
            chmod +x "$FFPROBE_PATH"
            echo "Set execute permissions on $FFPROBE_PATH"
          else
            echo "FFprobe not found at $FFPROBE_PATH" >&2
            ls -la "ZQ SFX Audio Splitter.app/Contents/Resources"
            exit 1
          fi

      - name: Verify Binary Architectures
        shell: bash
        run: |
          echo "Verifying architectures of ffmpeg and ffprobe..."
          file "ZQ SFX Audio Splitter.app/Contents/Resources/ffmpeg"
          file "ZQ SFX Audio Splitter.app/Contents/Resources/ffprobe"

      - name: Confirm Execute Permissions
        shell: bash
        run: |
          echo "Confirming execute permissions on binaries and executable..."
          ls -la "ZQ SFX Audio Splitter.app/Contents/MacOS/ZQ SFX Audio Splitter"
          ls -la "ZQ SFX Audio Splitter.app/Contents/Resources/ffmpeg"
          ls -la "ZQ SFX Audio Splitter.app/Contents/Resources/ffprobe"

      - name: Final App Bundle Verification
        shell: bash
        run: |
          echo "Final App Bundle Structure:"
          find "ZQ SFX Audio Splitter.app" -print

      - name: Check Executable Dependencies
        shell: bash
        run: |
          echo "Checking dependencies of the main executable..."
          otool -L "ZQ SFX Audio Splitter.app/Contents/MacOS/ZQ SFX Audio Splitter"

      # Optional: Code Signing (Requires proper setup and certificates)
      # - name: Code Sign App Bundle
      #   if: success()
      #   run: |
      #     codesign --deep --force --verify --verbose --sign "Developer ID Application: Your Name (Team ID)" "ZQ SFX Audio Splitter.app"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: "ZQ SFX Audio Splitter.app"

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==5.7 pydub numpy

      - name: Clean Previous Builds
        run: |
          Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          Remove-Item -Force *.spec -ErrorAction SilentlyContinue

      - name: Download FFmpeg
        shell: pwsh
        run: |
          Write-Output "Downloading FFmpeg..."
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip" -OutFile "ffmpeg.zip"
          Write-Output "Extracting FFmpeg..."
          Expand-Archive -Path "ffmpeg.zip" -DestinationPath "."
          Write-Output "Listing contents after extraction:"
          Get-ChildItem -Name
          Write-Output "Finding extracted FFmpeg directory..."
          $ffmpegDir = Get-ChildItem -Directory -Name | Where-Object { $_ -like 'ffmpeg-*' } | Select-Object -First 1
          if (-not $ffmpegDir) {
            Write-Error "FFmpeg directory not found after extraction."
            exit 1
          }
          Write-Output "Extracted directory: $ffmpegDir"
          Write-Output "Moving FFmpeg binaries..."
          Move-Item -Path ".\$ffmpegDir\bin\ffmpeg.exe" -Destination ".\ffmpeg\ffmpeg.exe" -Force -ErrorAction Stop
          Move-Item -Path ".\$ffmpegDir\bin\ffprobe.exe" -Destination ".\ffmpeg\ffprobe.exe" -Force -ErrorAction Stop
          Write-Output "Cleaning up..."
          Remove-Item -Recurse -Force -Path ".\$ffmpegDir", "ffmpeg.zip"
          Write-Output "FFmpeg binaries downloaded and moved successfully."

      - name: Verify FFmpeg Binaries
        shell: pwsh
        run: |
          if (Test-Path "ffmpeg\ffmpeg.exe") {
            Write-Output "ffmpeg.exe is present."
          } else {
            Write-Error "ffmpeg.exe is missing."
          }

          if (Test-Path "ffmpeg\ffprobe.exe") {
            Write-Output "ffprobe.exe is present."
          } else {
            Write-Error "ffprobe.exe is missing."
          }

          Write-Output "Contents of ffmpeg directory:"
          Get-ChildItem -Path "ffmpeg" -Recurse

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --windowed --onedir --name "ZQ SFX Audio Splitter" audio_splitter_gui.py `
          --add-binary "ffmpeg\ffmpeg.exe;ffmpeg" `
          --add-binary "ffmpeg\ffprobe.exe;ffmpeg" `
          --hidden-import=tkinter `
          --hidden-import=pydub `
          --hidden-import=numpy `
          --exclude-module=test `
          --exclude-module=unittest `
          --exclude-module=email `
          --exclude-module=html `
          --exclude-module=xml `
          --log-level=DEBUG `
          --debug=all

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AudioSplitter-windows-build
          path: dist/